version : "3"
services:
  postgres:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=dontforget12
        - POSTGRES_DB=APILearning
      volumes:
        - postgres-db:/var/lib/postgresql/data
  api:
    build: .
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./:/usr/src/app:ro
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_NAME=APILearning
      - DATABASE_USERNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=dontforget12
      - SECRET_KEY=8c170a75ef0f564b9eeb9fa4f2f215e6288548d4c9200d0b7c0ec0094a4fb124
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    depends_on:
      - postgres
  
volumes:
    postgres-db:

